### ISSUE TITLE
Checkin when file not part of a list

### ISSUE THREAD

**Issue by kabtoffe** [tavikukko/Chrome-SP-Editor#1]
I tried editing a javascript resource file in an app web. Editing and saving worked fine but it fails on check in. Apparently check out was successful though and now I get an error about the file being checked out. The check in error text was something along the lines "file is not part of a list".
![js-error](https://cloud.githubusercontent.com/assets/10654778/5857313/6174973e-a253-11e4-9bc3-41d89faedbb2.png)

I'm guessing I could have avoided this by making it not check out and in... Any idea how to get it checked in? Also maybe the extension could do a check before checking out something it can't check in.

**Comment by tavikukko** [comment]
Hi,
And thanks for using this tool. I have not tested this to edit files in appweb, but looks like its also working :) . You could try to select the "Don't auto checkout / checkin" and "Don't auto publish" options and try to save again. And yes, to check the "chekout status" before saving is a good idea. Thanks.

**Comment by tavikukko** [comment]
Also, you always need to make a change in the file you are modifying, for example add some empty spaces. The tool will not save the file if there is no changes.
