### ISSUE TITLE
Access to SP Editor depends on size of F12 pane

### ISSUE THREAD

**Issue by kasperbolarsen** [tavikukko/Chrome-SP-Editor#107]
Browser Edge Version 109.0.1518.55 , installed SP Editor from the Chrome store, not Edge store.
If the F12 pane is fairly small I see the "SharePoint" menu item 
![image](https://user-images.githubusercontent.com/20593570/213150418-2afc2840-4a9b-420d-b432-3f6b3121abc1.png)

If I draw the pane to a larger size , and closes the pane using F12, then "SharePoint" is not shown the next time I hit F12.
Resizing the pane to a smaller size resolves the problem, but it is annoying.
PS. love the add-in

**Comment by tavikukko** [comment]
Hi @kasperbolarsen,
and thanks for reporting! 
I have seen this also, but normally when I restart the devtools, the sharePoint tab is there again. I think sometimes devtools has issue loading the extension, and there is nothing we can do. Normally, I use devtools positioned under the tab, not on the side, but nevertheless, that issue occurs sometime.

**Comment by kasperbolarsen** [comment]
Sorry to hear that, but I guess I'll just have to figure out the best setup where this happen less.
Thanks for the great work :-)

**Comment by tavikukko** [comment]
As for now I don't have idea how to improve the appearance of the tab, so will close this for now, thanks for using SP Editor!
