### ISSUE TITLE
Enhancement idea

### ISSUE THREAD

**Issue by kasperbolarsen** [tavikukko/Chrome-SP-Editor#108]
Would it be possible to add an option to enumerate the web parts on a Modern page and show the properties of the web parts, PropertyJSON is often of interest

**Comment by tavikukko** [comment]
Hi @kasperbolarsen !
I like the idea, would be handy. Most development is now happening here [pnp/sp-editor](https://github.com/pnp/sp-editor), so if you want you can move the idea there too, thanks!

**Comment by kasperbolarsen** [comment]
Sorry, this repository showed up as the first hit in a google search ;-) . I have copied it to pnp/sp-editor repository
