### ISSUE TITLE
Not possible to save  anymore

### ISSUE THREAD

**Issue by MarioMarfonePayComplete** [tavikukko/Chrome-SP-Editor#110]
Firstly thank you so much for this great extension that allow me to maintain many existing pages in our intranet (Sharepoint online); 
Since a couple of weeks it seems is not possible to save the changes in the aspx pages edited with the version 5.6.17 of Chrome SP editor extension; 
I can open the page from file editor, update the content but clicking CTRL+S to save my job the cursor seems in loop and the activity is not completed.
Tested by different people and in different computers managed by our organization and also using private compute (unmanaged). 
Thank you in advance for your help
Mario

**Comment by MarioMarfonePayComplete** [comment]
Found the problem and the solution. 
From July 2024 MS has disabled per default the execution of custom scripts in SP. 
This one has an impact also on SP Editor.
To solve it is enough to enable the custom scripts at site collection level or site level in SP admin center. 
Mario

**Comment by Gennady-G** [comment]
> From July 2024 MS has disabled per default the execution of custom scripts in SP.

@MarioMarfonePayComplete, does this have impact on Classic Pages, or only on Modern?
Do You have new site collection, or existing one?

**Comment by MarioMarfonePayComplete** [comment]
@Gennady-G 
In my case this one impacts on modern and classic pages.
Tested only in existing site collection
