### ISSUE TITLE
Right side Dock location doen't work with the Search option

### ISSUE THREAD

**Issue by kasperbolarsen** [tavikukko/Chrome-SP-Editor#111]
The right hand side dock location isn't optimal :-) unless using the entire screen
Version 128.0.2739.79 (Officielt build)

![image](https://github.com/user-attachments/assets/a5d257cb-f618-4c59-aace-86bcb3f47949)

**Comment by tavikukko** [comment]
Thanks @kasperbolarsen !
I think that need sshow/hide button, default to be hidden.

**Comment by tavikukko** [comment]
Repo lives now here btw :) https://github.com/pnp/sp-editor

**Comment by tavikukko** [comment]
@kasperbolarsen fixed in version 7.0.1 and its available already.
