### ISSUE TITLE
Page Editor not showing any options to edit?

### ISSUE THREAD

**Issue by siothelibrarian** [tavikukko/Chrome-SP-Editor#112]
Hello! 

I'm using version 5.6.17 because I downloaded the newest version and found that it doesn't allow page editing; however, I am running into another issue. I'm working in Chrome and I have the page I am trying to edit checked out and open in Editing mode. I have the developer tools open to the SharePoint Editor tab, and I am on the Page editor section, but all I am seeing is a blank code editor, with a blank white column next to it where the information about each web part should be: 
![image](https://github.com/user-attachments/assets/31213bea-0683-4679-ae8a-cd9e312236f9)

I'm not sure if this is a bug or just me doing something wrong because:
- the introductory video shows the tool working in Classic, and I'm working in Modern. I didn't see anything in the readme or instructions that says the tool is limited to Classic.
- the documentation discusses editing web part properties; I'm not trying to edit the properties of the web parts (in my case, text boxes), but the actual text inside them.

I've tried restarting the browser, reloading the page a couple times and reopening the console, and clicking between web parts on the page to see if that makes any difference, but there's no change to the Page Editor UI - it's always just blank.

**Comment by tavikukko** [comment]
Hi @siothelibrarian and thanks for the issue!
This version of SP Editor is not updated anymore, the Chrome Extension policies where upgraded to manifest v3 and this version of SP Editor does not work with it.

The Page Editor, what you have taken the screenshot, is indeed for Classic SharePoint WebpartPages, so it will not work for Modern pages. SP Editor does not have editor for Modern Webparts, as they are very easy to update from the property pane of the webpart.

If you are working on Modern SharePoint, please use the default edit mode of the page, or the property pane of each webpart to update the properties of the webpart.

Thanks for downloading the old version of SP Editor, but I encourage you to use the new version.

If you have any more questions, please don't hesitate to ask, cheers!

**Comment by siothelibrarian** [comment]
Hi Tomi! Thank you for the quick response. I think I was just mistaken about what the tool does; I found it while looking for options to edit the actual content of pages (as opposed to web part properties) because Microsoft has removed the ability to use SharePoint Designer/edit page code directly and not yet added accessibility features such as keyboard shortcuts back into the default editing options.

I was hoping this tool would help me bridge that gap so that I could continue to work in SharePoint effectively without being limited by my disability. It sounds like this isn't a good fit for that use case, but I've been really impressed with the tool and I think it might be helpful for some other work, so thanks for all your hard work on it!
