### ISSUE TITLE
External scriptlinks translated to lowercase

### ISSUE THREAD

**Issue by jpalo** [tavikukko/Chrome-SP-Editor#18]
Hi,
When adding external scriptlinks, the actual URL from which the file is fetched is translated to lower case at some point, making external scriptlinks not working whenever CDN enforces case sensitive file names.

E.g., https://cdnjs.cloudflare.com/ajax/libs/jStorage/0.4.12/jstorage.min.js becomes https://cdnjs.cloudflare.com/ajax/libs/jstorage/0.4.12/jstorage.min.js, and file isn't loaded as Cloudflare is case sensitive.

On the other hand Microsoft CDN works fine as it isn't case sensitive, so https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.2.1.min.js works fine although it ends up being queried as https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.2.1.min.js.

I did look through the code but didn't see any obvious .toLowerCase() that would've caused this, so posting issue here.

**Comment by tavikukko** [comment]
Hi @jpalo !
interesting... I will have a look on this. Thanks for reporting!

**Comment by tavikukko** [comment]
ok,
this is really interesting... if you reference local file "~sitecollection/Style library/testing.js" it will keep the format... if referencing from CDN it will make it lowercase..

**Comment by tavikukko** [comment]
So @jpalo, it seems to be that the customaction holds the format correctly but the SharePoint Control that renders the the link makes it lowercase... so there is not really anything to do..ideas?. If you want you can also create customaction using scriptblock property, then the format of the url will be kept. Its easy with PnP JS Console.

**Comment by tavikukko** [comment]
btw, I was wrong, all scriplinks will be lowercase, no matter if loaded from cdn or local file.

**Comment by tavikukko** [comment]
so @jpalo I will close this as it's not Issue with SP Editor, more related to SharePoint. You might need to change CloudFlare to another CDN provider.
