### ISSUE TITLE
Files are published even though "Publish a Major version on save" is unticked

### ISSUE THREAD

**Issue by andrei-markeev** [tavikukko/Chrome-SP-Editor#2]
Hi,

Not sure if it is a bug or just a feature that requires a better description :)
This is my configuration (in SharePoint tab in devtools):

[x] "Update changes to SharePoint" --- ticked
[  ] "Publish a Major version on save" --- not ticked

But then, if the file is already published as major version, and I save it from devtools, it gets published again as major version!
My expectation was that since I haven't checked "Publish a Major version on save", it would save minor version.

I was actually editing some files on production and was pretty sure that changes were not visible to anyone but then to my surprise they were :)

**Comment by tavikukko** [comment]
Hi Andrei,
good catch, I need to look on this one.
Is the list configured to allow minor versions? Could you verify that?
Thanks

**Comment by andrei-markeev** [comment]
Yes, it was.
It was just an ordinary Style Library actually. SP2013 onprem.
One of the files was checked out to me and it was correctly producing minor versions when saving via Chrome SP Editor. Other files I was lazy to check out and just started modifying them, and it turned out they produced major versions.

**Comment by andrei-markeev** [comment]
just a random guess...

in the source code:
```javascript
if (!this.publish) this.file.publish();
```
should it be the other way around? i.e. `if (this.publish) ..`?

https://github.com/tavikukko/Chrome-SP-Editor/blob/master/event.js#L95

**Comment by tavikukko** [comment]
There was a bug, this.publish was always undefined. Now fixed and new release published to Chrome WebStore.

**Comment by andrei-markeev** [comment]
Thanks :+1:
