### ISSUE TITLE
Script link remains here, cant be deleted because they are not visible (SP2013)

### ISSUE THREAD

**Issue by seaSide974** [tavikukko/Chrome-SP-Editor#20]
hi, 

Thanks for the use ful extension
I added a script link, then i cant see it in the list of web scripts links, due to some bug i believe ?
I deleted the extension from chrome, though the script link is still here.
How to uninstall it ? Thank you

**Comment by koltyakov** [comment]
Hey @seaSide974,

You can use PnP JS Console (a part of SP Editor toolsets) for this and run:

```TypeScript
pnp.sp.web.userCustomActions.get().then(console.log);
```

Then check for a script link user custom action in an array of custom actions, take its Id prop and delete the thing with:

```TypeScript
pnp.sp.web.userCustomActions.getById('31032f5d-d89a-4511-859e-3a9141b789f9')
	.delete().then(console.log);
```

Cheers!

**Comment by seaSide974** [comment]
oh great thx, stupid newbie question,how do you execute from the pnp js console ? Cant find a button run :) ?

**Comment by koltyakov** [comment]
Ctrl+D - there is a hint about the combination when opening a console:
![image](https://user-images.githubusercontent.com/7816483/31494560-74751e80-af5c-11e7-81ae-82ec2636d8b9.png)

**Comment by seaSide974** [comment]
Its not working for me

**Comment by seaSide974** [comment]
for the code : 
import pnp from "pnp";
pnp.sp.web.userCustomActions.get().then(console.log);

**Comment by koltyakov** [comment]
If you're using SharePoint 2013 On-Prem Accept headers should be defined strictly:

```javascript
import pnp from "pnp";
pnp.setup({
	sp: {
		headers: {
			Accept: 'application/json; odata=verbose'
		}
	}
});
pnp.sp.web.userCustomActions.get().then(console.log);
```

**Comment by seaSide974** [comment]
that works better thanks :) 
When i run pnp.sp.web.userCustomActions.getById('61db46e9-c27c-42a8-aec9-7a7373176785').delete().then(console.log);

it return null, and i still see it in the list,
nevermind this is a dev environment, no big deal. Good to know i can use pnp in future directly from here for sp2013

thx again

**Comment by ytterstrom** [comment]
I just tested on my SharePoint 2013 environment and I can delete customactions just fine. So if you run  
        pnp.sp.web.userCustomActions.get().then(actions => {
            console.log(actions);
        }); 
you see your custom action? And then you try to use the Id in pnp.sp.web.userCustomActions.getById('IdToDelete').delete();? For useractions on sitecollection you should use pnp.sp.site.userCustomActions....

**Comment by tavikukko** [comment]
Hi, missed the conversation here totally, but thanks @koltyakov  and @ytterstrom for backing me up! Im still thinking why @seaSide974 could not delete the CustomAction, in Scriptlinks nor in PnP JS Console. @seaSide974 can you share screenshot, log or the link what you tried to delete? Thanks for reporting this!

**Comment by seaSide974** [comment]
i ran the following as advice and to cover site and web scenario and it works :) thanks
Though i still cant see it in the scriptlinks menu. The environment cant be access by windows explorer, i guess some ports are blocked and thats why scriptlinks are not showing (pnp shows me 7 of them)

thanks for your help :)

import pnp from "pnp";
pnp.setup({
  sp: {
    headers: {
      Accept: 'application/json; odata=verbose'
    }
  }
});
pnp.sp.web.userCustomActions.get().then(console.log);
pnp.sp.web.userCustomActions.getById('9dfe7444-7153-49cd-b7b8-9828fc37b05a').delete().then(console.log);
pnp.sp.site.userCustomActions.getById('9dfe7444-7153-49cd-b7b8-9828fc37b05a').delete().then(console.log);
pnp.sp.web.userCustomActions.get().then(console.log);

**Comment by seaSide974** [comment]
there is no log showing or error for the scriptlinks menu, do you want me to check something else ? If not we can close the issue as i have a workaround :)

**Comment by tavikukko** [comment]
So, You used SP Editor to attach the link, but you never saw the link in the editor, but it was injected anyways, if i understood correctly? What I would like to know is, the format of the link you added. SP Editor can only handle links, no other formats, only url links.

**Comment by seaSide974** [comment]
Hi, that is correct.
I have added ~sitecollection/style library/my.js on the web and site coll level
Since i thought it was not working i also added http://mysite/style library/my.js

**Comment by tavikukko** [comment]
Link seems to be ok, you having custom masterpage?

**Comment by seaSide974** [comment]
No, ootb master page, sp2013.
But some port are blocked (Impossible to use sp designer for example) so maybe it is due to that ?

**Comment by tavikukko** [comment]
Its just javascript, so it should be fine, no ports should block SP rest calls, like you described earlier, the links get injected but SP editor does not show them? If there are errors, you should see errors in Chrome console if any. Could you check?

**Comment by seaSide974** [comment]
I don't get any error, you want to teamviewer my computer ?

**Comment by ytterstrom** [comment]
I think I found the problem. PnP js 3.0 introduced a different way of assigning request headers which is necessary for SP 2013. I created a pull request with the fixes (I hope I done it the right way).

**Comment by tavikukko** [comment]
Thanks @ytterstrom, great work! Im travelling at the moment, but will review and merge when back. Loog good at first sight and it makes sense.

**Comment by seaSide974** [comment]
Cool :) cant wait to test !

**Comment by tavikukko** [comment]
New release in chrome store, v2.4.4. @seaSide974 could you test in SP2013 and verify. Thanks.

**Comment by seaSide974** [comment]
![image 3 pnp](https://user-images.githubusercontent.com/6776269/31762253-f620b986-b4ba-11e7-9b4f-09a057e6aa7d.png)

I am sorry to announce you that we will close this issue and stop talking to each other (about this issue =) ) since it is working

Thank you !

**Comment by koltyakov** [comment]
Oh no! We'll be missing each other, friends! Until next interesting topic starter issue. =)

**Comment by bjdekker** [comment]
First of all thanks for this great Chrome extension! I noticed that since today I get an error that seems to be related to this issue and release 2.44 in SharePoint Online. When I click on the File editor in SharePoint Online I get the following error:
![image](https://user-images.githubusercontent.com/12426259/31770728-80c21544-b4d9-11e7-8ace-7fb2a6f9ca0a.png)
When I revert back to 2.4.3 everything is working fine again. As far as I can see, this was the only change in this release.

**Comment by tavikukko** [comment]
Yep, thanks @bjdekker for reporting. Will fix it right away, sorry about that. Should never code while travelling.

**Comment by ytterstrom** [comment]
Can confirm. If I remove $pnp.setup... alltogether from getFolders(), it works as expected in SharePoint-online. But no go for SP2013 in that case.

**Comment by tavikukko** [comment]
New release in chrome store, v2.4.5.

**Comment by seaSide974** [comment]
We have a workaround for SP2013, using PNP commands... so up to you guys :)

**Comment by tavikukko** [comment]
@bjdekker all should be good now, could you verify? @ytterstrom & @seaSide974 could you verify SP2013 that everything works as expected? Thanks!!

**Comment by bjdekker** [comment]
hi! just tested several scenarios and everything works as expected. Thanks!

**Comment by seaSide974** [comment]
Script links are still visible on SP2013 @tavikukko  +1

**Comment by tavikukko** [comment]
Great, will close this then. **Big thanks for everyone** working with this issue, really appreciated! Now, I will focus on the next release, with new feature related to Microsoft Graph.

**Comment by seaSide974** [comment]
Great keep on the good work.  Thanks everybody
