### ISSUE TITLE
Endless loading state after saving in file editor

### ISSUE THREAD

**Issue by johannes-z** [tavikukko/Chrome-SP-Editor#23]
When I edit a file with the file editor and save it, it sometimes happens that the loading state never ends, but still saves the file. You then have to reopen the console, re-enable the update/save as major options and browse back to the file in the file editor which can be annoying if that happens to often. It might be that this happens if you have more than one console / SP.Editor window open, but I can't confirm yet.

Also, if there is nothing wrong with the "saving" itself, how about remembering the state the SP.Editor was in for any given site? E.g. remembering the "Save to SharePoint"-options, remembering the collapsed/expanded folders in the file editor.

**Comment by Gennady-G** [comment]
>  it sometimes happens that the loading state never ends

+1. 
Yes, it sometimes hangs on .Saving..', and I reopen DevTools. imho it occurs if I have DevTools opened on few pages..

**Comment by Gennady-G** [comment]
> E.g. remembering the "Save to SharePoint"-options, remembering the collapsed/expanded folders in the file editor.

Even more, imho it is good idea to be able to access files from subsites (in my case I store sources in /portal/Style Library/, but test webparts on /portal/subsite/). So I need to use mappings or open another tab to quick change source in Style Lib (mappings do not work for *.html files)

**Comment by tavikukko** [comment]
Hi @johannes-z and thanks for reporting this. I have seen also this behaviour and think the problem is indeed the multiple consoles/sp-editor opened in another tabs. Let's see if there is something to fix this problem.
About saving the state of each site can be challenging. Maybe it could be possible to expand subsites also as @Gennady-G was suggesting. 
Than

**Comment by Gennady-G** [comment]
Thank You for response **tavikukko**!
I can create separate ticket, if needed)

Best regards,     
Gennady

**Comment by tavikukko** [comment]
no worries @Gennady-G I think it's a good idea, If it's performs well I will try to add that functionality. The issue mentioned by @johannes-z seems to be quite easy fix, hope to release it soon. Thanks guys!

**Comment by tavikukko** [comment]
New version in Chrome WebStore, Version 3.2.1.

**Comment by tavikukko** [comment]
@Gennady-G support for subsite browsing and reorganized save buttons, hope this helps. Latest version release, v3.3. Cheers!

**Comment by Gennady-G** [comment]
Thank You much @tavikukko ! :)
