### ISSUE TITLE
[Really minor issue] Missing Instruction

### ISSUE THREAD

**Issue by seaSide974** [tavikukko/Chrome-SP-Editor#25]
hi guys !
Been using your app more and more recently :) i see that there is a new instruction panel which guide us better ! thanks for that

there is a missing code i think for that ?

Have a great day 👍 

"PnP JS Console
Write TypeScript using PnP-JS-Core definitions and execute on current context
ctrl + d to execute
for sp2013 change the headers of the request:"

**Comment by tavikukko** [comment]
Yes @seaSide974 thats new panel in SP Editor.  The idea is that I will try to add more detailed instructions in the future. In that PnP JS Console instructions, the headers settings are missing, will update in next release, cheers!

**Comment by seaSide974** [comment]
Great ! keep the good work :) getting more colleagues using it !
