### ISSUE TITLE
Not an issue, just want som guiding

### ISSUE THREAD

**Issue by ytterstrom** [tavikukko/Chrome-SP-Editor#26]
Hi!
I really love your extension and use it almost daily in my projects, and I would really like to contribute more. I have some questions, about the best way to develop and debug the code. Previously I have been using VS Code, and the "debugger for chrome"-extension. But if I open the debug tools in Chrome, where your extension reside, VS code detach its debugger. How is your setup? How do you develop and debug your code?

**Comment by tavikukko** [comment]
Hi @ytterstrom !
Im not using vscode for debuging, but that would be nice.
So what I do is the following:
- Clone the project
- Open chrome extensions tab and "load unpacked extension..." and select the project folder
- Open SP site and hit F12 to open the devtools and SharePoint tab
- Detach the devtools from the browser
- Hit "Ctrl + Shift + I" to open the devtool of the extension :)
- Now you will see the the code behind the SP Editor and you will be able to add breakpoint to your code, console.log and so on.

If you make changes to the code, you need to reopen/refresh the page to get the code loaded.
In you make changes to the content scripts (introduced in the manifest.json), sometimes you need to go back to the extensions and hit "reload" button.

If you need more help, please do not hesitate to ask!

Thanks!

**Comment by ytterstrom** [comment]
Thanks for info. I got it working. I am closing the issue
