### ISSUE TITLE
Error in the file editor

### ISSUE THREAD

**Issue by afwilliams** [tavikukko/Chrome-SP-Editor#27]
Erro in the file editor.

![image](https://user-images.githubusercontent.com/791622/33629294-8159cbba-d9d1-11e7-9c74-e25270c5e5cb.png)

![image](https://user-images.githubusercontent.com/791622/33629734-1ee3c2ae-d9d3-11e7-803b-58f9b1f6882a.png)

**Comment by tavikukko** [comment]
ok, got it, seems to be on-premise (2016?) and the reason is that _spPageContextInfo does not have WebId property.

**Comment by tavikukko** [comment]
Fixed, new Version 3.3.1 on chrome web store. Thanks @afwilliams for reporting.

**Comment by afwilliams** [comment]
Hi, I'm sorry no to answer before, the version is SharePoint 2013

**Comment by afwilliams** [comment]
Excelent, it work! :-)
