### ISSUE TITLE
Show root web folders, if "File Editor" clicked on subsite

### ISSUE THREAD

**Issue by Gennady-G** [tavikukko/Chrome-SP-Editor#28]
Hi @tavikukko !

Subsites tree is cool, but can You show it if SP-Editor is opened in subsite context? 

For example if I open Editor on site-collection level I see StyleLibrary. Then I can navigate to http://devportal/dev subsite and it is still accessible.

![2017-12-06_173507](https://user-images.githubusercontent.com/5569346/33669873-4013e600-daac-11e7-9384-6824285bcbf2.png)

But if I click File Editor from subsite I see only subsite folders and no webs:

![2017-12-06_174253](https://user-images.githubusercontent.com/5569346/33670047-b9a0878a-daac-11e7-9999-a2aba8eb5e49.png)

As I understand there are different contexts.. If it is not very hard - can You allow to access 'Style Library' from subsites?

**Comment by tavikukko** [comment]
Hi @Gennady-G,
I think I get your point here. The thing is, if you open sp-editor and click file-editor, you will see the folders, files and webs of that web. Now, if you browse to a subweb, sp-editor will have wrong context. You should click file-editor from the left menu to catch the new context. So you will never see the parent web folders/files/webs of the current context. 
So you are suggesting to render always the whole "structure" of current site collection, to be able to manage everything from where ever you are at the moment? To keep things simple, I think its easier (and faster) just to press file-editor link again to update the file-editor tree and then browse that webs folders/files/webs. web properties / list properties / webhooks also use this same logic, so I think there is a reason to follow that routine. If you want to browse everything, the just go to the rootweb and there you will be able to see the whole structure. What do you think?

**Comment by Gennady-G** [comment]
Greetings @tavikukko !

> So you are suggesting to render always the whole "structure" of current site collection, to be able to manage everything from where ever you are at the moment? 

Yes, something like this. This is because I always place my html/js/css sources in 'Style Library', but link them as Content Query Webparts _on subsites_. I connect sources with local folder, and update using Your extension(when I save local file, SP-Editor updates file in SP library):

![2017-12-06_201515](https://user-images.githubusercontent.com/5569346/33678008-44696830-dac3-11e7-9836-dd074f8eb324.png)

All is great but sometimes I need to update *.html too, so I  jump between site collection/subsite, or keep both tabs opened.

> You should click file-editor from the left menu to catch the new context. So you will never see the parent web folders/files/webs of the current context.

Hehe, in my case I **want** to see upper-level context :)

Is it hard to change context depending on web? For example show the whole structure, and if clicked "dev subweb" - change to subweb context? Or something like this.. I don't know how You made it.

If it is hard or breaks application logic - no problems, I can live without it :) Your application already helped me a lot, I can drop VS and use Your tool only for O365 development)

**Comment by tavikukko** [comment]
In chrome extensions, there is event to track browser events and [webNavigation.onClompete](https://developer.chrome.com/extensions/webNavigation#event-onCompleted) would be the one to be used in this case. So I think it could be doable, but would break then the basic logic of the application, which is, to stay in the current web/page context.
About .html files, as I can see from your picture, the chrome source tab is showing these .html files, but you cannot update those the same way as js/css files? I think that was restriction in chrome extensions and there might not be anything to do, but I can take a look at the API again if there is any updates on this.

**Comment by Gennady-G** [comment]
Hi @tavikukko !
> think it could be doable, but would break then the basic logic of the application
No, please don't worry about it!

> About .html files, as I can see from your picture, the chrome source tab is showing these .html files, but you cannot update those the same way as js/css files? I think that was restriction in chrome extensions and there might not be anything to do, but I can take a look at the API again if there is any updates on this.

Yes exactly. html does not sync and I use Your editor. 

p.s.: haven't You made any changes today? Noticed that file does not sync every time I hit 'Save' in vsCode.. I will test later and add details. Not sure, it could be my local chrome/vscode bug..

**Comment by tavikukko** [comment]
No changes since December 5, 2017.
If you find any problem, just create new issue with details and I will have a look.
Will close this for now.

Thanks @Gennady-G!

**Comment by Gennady-G** [comment]
Thank You much **tavikuko**! :)
