### ISSUE TITLE
File editor options

### ISSUE THREAD

**Issue by johannes-z** [tavikukko/Chrome-SP-Editor#29]
I'm not sure if this is possible with the integrated file editor, but it would be nice if there were some basic options, like using spaces instead of tabs, default indentation etc.

**Comment by tavikukko** [comment]
Thanks @johannes-z,
monaco-editor has [settings](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorconstructionoptions.html) and with these you can give default options for the editor. I think there is no space in the DevTools limited area for the editing the settings and those would be always set to default when you close the extension. But if you have suggestion for better default settings, please create PR or issue with the settings values. You can find the default settings for File Editor [here](https://github.com/tavikukko/Chrome-SP-Editor/blob/master/app/tags/fileeditor.js#L17). Thanks.
