### ISSUE TITLE
Wont work in personal sites

### ISSUE THREAD

**Issue by admiralman** [tavikukko/Chrome-SP-Editor#3]
Does not seem to be able to function correctly in personal sites within Sharepoint Online. Logged in with the same account I can drag and drop files into the Style Library. Otherwise, great tool.

https://shlp-my.sharepoint.com/personal/first_last_domain_com

**Comment by tavikukko** [comment]
Hi,
seems to be that the front page of personal site (_layouts/15/onedrive.aspx) is something special. If you go to [https://shlp-my.sharepoint.com/personal/first_last_domain_com/_layouts/15/viewlsts.aspx](https://shlp-my.sharepoint.com/personal/first_last_domain_com/_layouts/15/viewlsts.aspx), the tool is working normally. But you cannot get the custom scripts / css files loaded in the front page. Good catch, I will add a note to README.
Thanks!
