### ISSUE TITLE
Is chromium supported?

### ISSUE THREAD

**Issue by jeancallisti** [tavikukko/Chrome-SP-Editor#34]
I'm in a very strict dev environment where I can't install a browser on my 32-bit dev machine.

Therefore, I picked the only portable version of Chrome that I could think of : the latest build of Chromium 32-bits, which is build 541803
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Win/541803/

I've installed SP Editor into it and it's kinda working, except a few errors here and there : It can't save the CSS files directly from the styles panel (I must go to the file Editor and do "Save") and I have a fully blank panel in the "Page Editor" Panel. Also I have lots of errors on the "Modern Properties" and "Site Designs" panels but I'm guessing that this is because I'm SP2016 Enterprise on-premise.

Anyways : any objection to Chromium?

**Comment by tavikukko** [comment]
Hi @jeancallisti and thanks for trying out SP Editor!
Thats interesting setup you got there, and I have to say I do not have any experience with SP Editor with that version. Modern Properties / Site Designs and some other features also only work on O365.
Page editor should work in OnPremise anyways. What kind of development you are doing?

**Comment by tavikukko** [comment]
If you can track the error messages from console in features that are not working, especially Page Editor, that would help me to solve the issue.

**Comment by jeancallisti** [comment]
Thanks for the lightning-fast answer!
I'm just doing some on-premise SP2016 Enterprise development, from a client machine (not from within the farm). Our client machines have very strict policies and we don't have administrator rights. Hence the Chromium.

So, the good news is : 
- you explained why Modern Properties and Site Design panels don't do anything for me (I'm proud of my intuition despite the mess that is SharePoint)
- at first, the automated saving of the CSS file was not working because I used a (very!)  old build of Chromium by mistake, but it works fine in the latest one.

The bad news are :
- nothing happens when I press Ctrl+D in the pnp js console panel.
- the page editor still doesn't work in my recent Chromium build (still all blank). I'll check the console and post again.

**Comment by jeancallisti** [comment]
Also, if you're wondering why I'm desperately trying to use SP Editor despite the obstacles, it's because you have the ultimate power feature : linking Scriptlinks that are outside the site collection, even in an on-premise install. With some work I could (maybe) work out the scriptblock trick you used, but it would require me to write some (fragile, considering my skills) javascript. So, SP Editor it is.
More generally, I'm diving into the world of Javascript injection to replace the old practice of Master Page edition. So, I'd better use the best tools.

**Comment by koltyakov** [comment]
> Our client machines have very strict policies and we don't have administrator rights. 

Outch... they squeeze your balls, man! ;)

**Comment by jeancallisti** [comment]
Yes they do.

EXCELLENT NEWS : do you know the way I told you that I had first used a very old Chromium by mistake, and then switched to the latest one and it didn't solve the issues? Well, guess what. The old one was still opened alongside it, and... it turns out that if you run the new Chromium while the old one is still open, then Chromium will use everything from the old one (DLLs, settings, etc.). So you click on the latest chrome.exe and nehind the scenes it runs the old chrome.exe.
After I closed all the Chromium instances, and ran only the latest chromium, then everything worked as expected. No error messages and no weird behaviours. Hurray!

This discussion thread can be marked as resolved.

**Comment by tavikukko** [comment]
great battle @jeancallisti ! 
If you get any more questions, just open issue, glad to help ( and big thanks to these wizards --> @koltyakov & @ytterstrom )!
