### ISSUE TITLE
How to execute the script in the PnP console?

### ISSUE THREAD

**Issue by jeancallisti** [tavikukko/Chrome-SP-Editor#35]
This question might sound stupid but maybe I'm missing something.

In SP Editor, how do you run the script in the pnp js console? There are no buttons, it only looks like a text editor. Am I missing the button because of my chaotic dev environment, or am I missing some shortcut?

**Comment by jeancallisti** [comment]
OK, Ctrl+D. I was so eager to test the plugin that I missed the big fat welcome page containing the help. Sorry for cluttering the forum.

**Comment by koltyakov** [comment]
![image](https://user-images.githubusercontent.com/7816483/37163531-18a7192a-2309-11e8-8674-915f36545c08.png)

**Comment by jeancallisti** [comment]
Well I hate to sound stupid a second time, but nothing's happening when I press Ctrl+D. I have a hard time figuring out of it's because of my portable Chromium environment.

**Comment by koltyakov** [comment]
Do you have console opened? It should be expanded before switching to SP Editor tools. Otherwise, `Esc` does nothing.

**Comment by koltyakov** [comment]
Also, if you're dealing with SP2013 don't forget to place PnPjs setup at the beginning of the script:

```typescript
pnp.setup({
  sp: {
    headers: {
      Accept: 'application/json;odata=verbose'
    }
  }
});
```

**Comment by ytterstrom** [comment]
Or use the snippet snip-headers to insert headers necessary for SP2013.

**Comment by jeancallisti** [comment]
OK, I didn't get that the console needs to be open alongside it to actually see the results (duh!). I don't know what I was expecting. I guess after being forced to use IE11 for way too long, I expected some kind of magical step-by-step execution interface directly in the pnp panel ;-)

**Comment by tavikukko** [comment]
I really should write those instructions and probably do a webcast guiding / demonstrating all the features :)
thanks again @koltyakov & @ytterstrom \o/
