### ISSUE TITLE
Efter upgrade to PnPjs the snippets does not work

### ISSUE THREAD

**Issue by ytterstrom** [tavikukko/Chrome-SP-Editor#39]
...Or am I doing something wrong. Maybe some of them should be rewritten, but I who is in some project still stuck on SP2013 rely heavily of the "snip-headers" in order to have support for onprem.

**Comment by tavikukko** [comment]
ok, cool, I just removed them cos it was not compatible with pnpjs. I have the plan to add them back (this evening), and I will start with headers snippet. Thanks @ytterstrom for pointing it out!

**Comment by tavikukko** [comment]
Published new version 4.1.0, snippets restored, updated monaco editor and added more scripts in the initial screen.
