### ISSUE TITLE
Failing to "Save" not detected

### ISSUE THREAD

**Issue by jeancallisti** [tavikukko/Chrome-SP-Editor#40]
This is more of a suggestion than an issue : when a file can't be saved (for whatever network reason) in the "file editor" panel, then the spinning wheel spins forever and nothing happens. 

The issue is that it locks the file Editor panel. You can't swap files and you can't copy and paste the code as it is (to save it somewhere else until you fix the issue). The only solution to exit this deadlock is to reload the page and/or to close and reopen SP Editor.

It would be nice if SP Editor detected that something is wrong, displayed an error message, and came back to the file.

**Comment by tavikukko** [comment]
Thanks @jeancallisti, I will have a look when back from vacation, it is a good suggestion.

**Comment by tavikukko** [comment]
cant repro, please open is still issue.
