### ISSUE TITLE
More of a question how to implement...

### ISSUE THREAD

**Issue by ytterstrom** [tavikukko/Chrome-SP-Editor#41]
The page editor does not work for modern pages. I am thinking about how to implement the [get-pnpclientsidepage](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpclientsidepage?view=sharepoint-ps), [add-pnpclientpagesection](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpclientsidepagesection?view=sharepoint-ps) and [add-pnpclientsidewebpart](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/add-pnpclientsidewebpart?view=sharepoint-ps). Do you have any suggestions or direction how to best proceed?

**Comment by tavikukko** [comment]
Cool idea @ytterstrom ! I think it should be own functionality, not baked in to Page editor. I think you can copy the Page editor tag code and use it as a base, If you want to see the code what its generating (You can use fileeditor to see the markup what generated when adding webparts and sections to modern page ). The to get the actual CSOM payloads you need to run powershell to find out the right payload (I think you know this already). The thing with modern pages is that they are easy to edit/update, so Im not sure what the use case would be?

**Comment by koltyakov** [comment]
Guys,

There is REST API for Modern pages.

The methods are implemented in PnPjs - [more details](https://pnp.github.io/pnpjs/sp/client-side-pages.html).

**Comment by tavikukko** [comment]
thanks @koltyakov, 
Im still using pnp-js-core in the other parts of the tool, so i need to update to pnpjs before we can go forward with this. I also have another idea, as this "modern editor" would not really need a gui.. so what im thinking is that we could have "sp editor cli". I have already been testing a library which mimics a terminal/console and you could run commands like in o365-cli / powershell in the browser. Of course those would actually use javascript behind the scenes, but still it would be very powerfull and fast to run simple commands without need to open PS/Terminal. What do you think? 
![screen shot 2018-08-10 at 9 34 46](https://user-images.githubusercontent.com/2223355/43942438-b4f2ab50-9c80-11e8-9e48-dbea95bcaff0.png)

**Comment by tavikukko** [comment]
This sampleis just a scripteditor webpart running in SharePoint using this library https://github.com/rohanchandra/javascript-terminal. It seems simple enough and has easy way to add your own commands. So I think only what needs to be implemented to this library is the autocomplete of the attributes/parameters of the custom commands (commands would execute PnPjs).

**Comment by ytterstrom** [comment]
What I am looking for is a way to easily "mock" a page with different sections and client webparts including their configuration. Regarding classic pages you can quickly edit the webpart properties using the page editor which is a convenient way, instead of edit the page in the gui and change the properties. of course you can also do this using powershell or rest api, but the involves some "plumbing". 

Maybe I am asking for too much, and it would result in some "bloating" of the tool...

Regarding a terminal/console. If it runs Javascript in the background, what is the benefit of using it instead of pnpjs console, is it the autocomplete of commands?

**Comment by tavikukko** [comment]
@ytterstrom updated the lib to PnPjs, so the needed clientside methods should be available to your needs.

**Comment by tavikukko** [comment]
closing
