### ISSUE TITLE
Script Sequence

### ISSUE THREAD

**Issue by pealmasa** [tavikukko/Chrome-SP-Editor#49]
Trying to insert new script located in style library but need this custom scripts to be last loaded after all other SP OOTB scripts. Set sequence to max aprox. 65000 but still referencing on same place in the page above other scripts. Understand sequence should be for SP Editor added scripts but any way to accomplish this?

**Comment by tavikukko** [comment]
Hi @pealmasa !
I think you need to use something like [this](https://gist.github.com/tavikukko/acecccd97cf26300cdb9)
inside your script to be sure the OOTB SharePoint scripts are loaded before your script runs.

```
document.addEventListener("DOMContentLoaded", function(event) {
    SP.SOD.executeFunc('sp.js', 'SP.ClientContext', function() 
    {
        ExecuteOrDelayUntilScriptLoaded(getAnnouncements, 'sp.js');
    });
});
```

**Comment by tavikukko** [comment]
any luck @pealmasa ?

**Comment by pealmasa** [comment]
@tavikukko it worked perfectly. Thanks!

**Comment by tavikukko** [comment]
great!
