### ISSUE TITLE
Refiners and Refinement Filters in search

### ISSUE THREAD

**Issue by forgetalex** [tavikukko/Chrome-SP-Editor#51]
Hi,

currently there is no option to pass refiners or refinement filters to the search. I would like to implement this feature if that would be ok.

Kind regards, Alex

**Comment by tavikukko** [comment]
yes @forgetalex, 
I have been thinking this too but have not had the time.
So please, all contributions are very welcome! 
Thanks!

**Comment by tavikukko** [comment]
Thanks @forgetalex for you contribution. Just pushed new version with your contribution of RefinementFilters feature (added also SortList & SourceId), cheers!
