### ISSUE TITLE
SPEditor is blocking alertify

### ISSUE THREAD

**Issue by cysieks** [tavikukko/Chrome-SP-Editor#56]
I really appreciate the tool you created, but recently found that SPEditor is blocking alertify functionality. When you click on dialog window, the dimmer is retained, which blocks webpage content from any interactions.

To reproduce:
1. Go to https://alertifyjs.com/alert.html
2. Click Run
3. Click OK on dialog
4. Page is dimmed, and you cannot click Run once again.

When SPEditor is disabled, everything works fine.
Chrome Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by cysieks** [comment]
This is related to injected stylesheet by SPEditor:

.alertify, .alertify.show {
    transition: all 0.33s cubic-bezier(0.25, 0.8, 0.25, 1) 0s;
}
injected stylesheet
.alertify {
    position: fixed;
    background-color: rgba(0, 0, 0, 0.3);
    left: 0px;
    right: 0px;
    top: 0px;
    bottom: 0px;
    width: 100%;
    height: 100%;
    z-index: 99999;
}
injected stylesheet
.alertify, .alertify *, .alertify-logs > *, .alertify.show {
    box-sizing: border-box;
}

**Comment by tavikukko** [comment]
Hi @cysieks and thanks for opening the issue!
I think the only way to fix this is to change the classnames in the css/js related to alertify.
Or any other thoughts?

**Comment by cysieks** [comment]
Hi, thanks for quick response.

Yes, if you change the class names to something unique, the problem will be resolved. I suggest using speditor prefix. e.g. .speditor_alertify

**Comment by tavikukko** [comment]
this is fixed in the edge version of this extension (not using alertify anymore )
