### ISSUE TITLE
CSS ScriptLink is deployed but not visible in SP Editor "Scriptlinks" tab

### ISSUE THREAD

**Issue by Gennady-G** [tavikukko/Chrome-SP-Editor#58]
Greetings!

Subj. I was able to successsfully deploy site-collection scope CSS, but cannot remove it because don't see it 

Best regards,
 Gennady

**Comment by tavikukko** [comment]
Hi, how did you deploy it?

**Comment by Gennady-G** [comment]
Hi @tavikukko!

Cannot reproduce. I think I understand - I switched all my extensions to start 'onclick':

![2019-08-22_110834](https://user-images.githubusercontent.com/5569346/63494265-634fec00-c4ce-11e9-85fb-0bbaeeaeb51a.png)

Then it is off by default and turns on only on click and F5..
![2019-08-22_110827](https://user-images.githubusercontent.com/5569346/63494275-68ad3680-c4ce-11e9-8894-176877ceadc1.png)

So this is my error, please excuse me for troubling! :)
