### ISSUE TITLE
Using quotes breaks link removal

### ISSUE THREAD

**Issue by jdtoth** [tavikukko/Chrome-SP-Editor#6]
Love this extension! I really wanted to use it to bust the SPO cache, so I threw in some JS code ... It works, but it appears to break the **removal** of that specific script link. 

Example:

~sitecollection/webparts/custom.css?v='+Date.now()+'

**Comment by tavikukko** [comment]
Does that work in the page? Interesting. I just fixed some bugs and released 1.4 version of the tool. I will have a look on this.

**Comment by tavikukko** [comment]
ok, just tested and I was able to remove it.
added: 
~sitecollection/webparts/custom.css?v='+Date.now()+' 
and it removed correctly. Can you try again?

**Comment by tavikukko** [comment]
@jdtoth update the extension to 1.4 version and try again. Or then there might be something else in your page breaking it.

**Comment by jdtoth** [comment]
I stand corrected - I was running 1.4 w/ disabled cache already but now that I've signed out/in again the links show up. Again, thanks.

I think we just found a GREAT, previously undocumented feature!

**Comment by jdtoth** [comment]
Just realized this creates a static string, so it won't work to bust the cache. Any way around this using your extension?

**Comment by tavikukko** [comment]
When do you have problem with the cache? When developing / editing files, and when you refresh the page you still get old version?
When using chrome developer tools, you can disable the cache, heres instructions for that https://github.com/tavikukko/Chrome-SP-Editor#disable-chrome-developer-tools-cache

If you just want to bust the cache when you are done with the editing, then just delete the scriptlink and recrete it with new querystring value and all browsers will get your latest changes
