### ISSUE TITLE
Graph Man Sign in not working 

### ISSUE THREAD

**Issue by thomyg** [tavikukko/Chrome-SP-Editor#60]
I'm trying to add a new feature that requires Microsoft Graph calls.

In order to get up and running, I try to mimic what is done in Graph Man. But I'm even not able to sign in with the default Graph Man.  

Using the latest version 5.4.4 I get a different behaviour for trying the extension in the standard and the dev way.

When I use the standard version of the extension I get the following error after clicking Sign in with Microsoft:
  
![image](https://user-images.githubusercontent.com/10920072/67625909-d7976a80-f844-11e9-8571-04930d237f34.png)

When using my local dev version of the extension I get the following:

![image](https://user-images.githubusercontent.com/10920072/67625926-001f6480-f845-11e9-9e7c-0b3c107794db.png)

Is anybody seeing the same? Any hints what I'm doing wrong? Thx!

**Comment by tavikukko** [comment]
Hi @thomyg !
I will have a look, it might be that the Graph Man feature is not currently working. You can also use PnPjs to access graph api.

**Comment by thomyg** [comment]
HI @tavikukko!

Thx for looking into it.

In terms of PnPjs -> Don't I need a token to talk to the Graph? I thought I need to do the same dance as in Graph Man to acquire the bearer token. Am I wrong here?

**Comment by tavikukko** [comment]
You can check the PnPjs Console functionality. When you open PnPjs Console, there is some sample code, and one of them accesses Graph (if fetches Groups). You need to be in modern page when you run it (ctrl-D). There is also some instruction in the comment of that code block to make sure the aad app of SharePoint granted correctly.

**Comment by thomyg** [comment]
You mean:

`// using @pnp/graph (modern page in browser)
// before using @pnp/graph, you need to grant needed API permissions
// to 'SharePoint Online Client Extensibility Web Application Principal' AAD Application
// from https://aad.portal.azure.com
import { graph } from "@pnp/graph"

if ((window as any).moduleLoaderPromise)
(window as any).moduleLoaderPromise.then(e => {
    graph.setup({
        spfxContext: e.context
    })

    graph.groups.get().then(grps => {
        console.log(grps);
    })
})
else console.log("to work with graph, switch to modern page!")`

Will try to play with this in the coming days. Keep you posted! Thx man!

**Comment by tavikukko** [comment]
yes thats the one

**Comment by tavikukko** [comment]
Fixed GraphMan login (take the latest), but it will take some time to publish cos google is doing in-depth review of the extension. If you want to develop something related to Graphman, I need the local version url of the extension which is always generated when locally developing. you can see this url when cheking the sources of the local extension using inspect feature. it will be formatted like this chrome-extension://lmlnofomaajjajmgkpoppmkhbelldadl/app/panel.html where "lmlnofomaajjajmgkpoppmkhbelldadl" is unique per developer. So provide that to me and will add it to the reply urls of the AAD App.

**Comment by thomyg** [comment]
Thx @tavikukko !

Calling graph within panelsqqueries.js works now with the following code: 
`if (window.moduleLoaderPromise) {
      // polyfill for _spPageContextInfo on modern sites
      window.moduleLoaderPromise.then(function (e) {
  
        $pnp.graph.setup({
          spfxContext: e.context
      })
      
      $pnp.graph.me.joinedTeams.get().then(function (teams) {
        var teamslists = [];
      console.log(teams);  
        teams.forEach(function (team) {
          teamslists.push({ displayName: team.displayName, teamsId: team.Id });
        });

    })`

Thx for your hints! Don't think I need the added reply url at the AAD with that. Happy to close that issue and I open the next one with a new question ;)

**Comment by tavikukko** [comment]
fixed in 5.4.5, thanks for reporting @thomyg !
also released 5.4.6 (still under review by google) for some sample code how to access graph endpoint using PnPjs Console using GraphMan.
