### ISSUE TITLE
On the on-prem SharePoint site previously added script link references are getting added automatically in a regular basis

### ISSUE THREAD

**Issue by LakshmiMurugavadivelu** [tavikukko/Chrome-SP-Editor#61]
Hi Team, 
I have a issue regarding the SP editor script links we are using script links in our on-prem SharePoint site for adding required js and css file references. we are updating the script link references when ever required or when ever there is a new change comes through.
I have noticed on 11th November 2019 all the previously used and deleted script-links references are added to the script editor automatically in all our site collections with out our knowledge.

For example if I removed one file reference and added a new location of the same file when this issue triggers i can see both the reference links on the SP editor the one which i deleted and the new one. this issue happens in all the sitecollections. And this issue has been noticed periodically.

I am not sure if we are missing any settings or when ever there is a new upgrade to script editor this issue triggers out? I can see 9th November there was an upgrade on SP editor so I have a doubt may be that triggered this issue? 
If anyone has already come across this issue or any one know the cause for this let me know. for more information let me know.

Thank You,
Lakshmi

**Comment by tavikukko** [comment]
Hi @LakshmiMurugavadivelu and thanks for reporting!
I tested with O365 and all seemed to work ok there. I will test on-prem version next week. Can you specify which SP version you were using? And also do you get any errors to console?

**Comment by LakshmiMurugavadivelu** [comment]
Hi Tavikukko,
Thank you for your response we are using Sharepoint 2016 version. Not getting any error in the console. 
Thank you, 
Lakshmi

**Comment by LakshmiMurugavadivelu** [comment]
Hi Tomi,
Again this morning all the old references are added in the SP Editor automatically not sure what is causing this issue. Let me know if you have any idea. 

Thank you, 
Lakshmi

**Comment by tavikukko** [comment]
Just to clarify:
1) You try to remove scriptlink, but it does not get removed? 
2) the old scriplink gets removed but appears after some days? 

if the second option, then this is not related to SP Editor

**Comment by tavikukko** [comment]
just tested in SP2016, added and removed scriptlinks, all worked fine.

**Comment by LakshmiMurugavadivelu** [comment]
2. The old script link gets removed but appears after some days.

**Comment by tavikukko** [comment]
ok, here is some ideas to check i your environment: 
1) It might be that you have deployed your custom actions (which installs the scriptlinks) using Feature framework and for some reasons those features are reactivated and the scriptlinks are re-added.
2) One another option could be that you have some script/job adding those links again to the site collection.

**Comment by tavikukko** [comment]
@LakshmiMurugavadivelu any updates? I would like to close this, seems not to be related to SP Editor.

**Comment by LakshmiMurugavadivelu** [comment]
Hi Tomi,
Thank You for your response yes you can close this. i will update you if i
come to know the cause.

Thank You,
Lakshmi

**Comment by tavikukko** [comment]
ok,
thank you @LakshmiMurugavadivelu , please create new issue, if you think its related to SP Editor.
