### ISSUE TITLE
CSS File update won't save

### ISSUE THREAD

**Issue by jimbotronn** [tavikukko/Chrome-SP-Editor#62]
I see the pop up text that says updating file but it doesn't give me the confirmation message that the file is saved, which is true because the file didn't get updated.  In chrome developer it shows 400 bad request error for the getfolderbyserverrelativeurl api call.  The same function seem to work on on a different site but nothing has changed other than I had to reinstall chrome on my laptop so I can't figure out what's causing it.

**Comment by tavikukko** [comment]
Hi @jimbotronn 
and thank you for opening this issue. 
Could you provide me the url from developer tool network tab, which gives the 400 error?
what environment are you working on, Online, on-prem13/16/19?

Thanks

**Comment by jimbotronn** [comment]
Organization is strict about their stuff so I took out the site address.  I think you are looking for what comes after the api code anyway.  

This URL below throws the 400 (Bad Request) error
**GET https://[siteaddress]/departments/MaterielSystems/_api/web/getFolderByServerRelativeUrl('%2Fdepartments%2Fmaterielsystems%2Fsiteassets%2Fstyles')/files('sc%2520suppliers%2520page.css')**

Here's the URL from another SharePoint site that SP Editor was able to update and save css file correctly even though it throws the 500 (Internal Server Error)
**POST https://[siteaddress2]/sites/MaterielSystems/_api/web/getFolderByServerRelativeUrl('%2Fsites%2Fmaterielsystems%2Fsiteassets')/files/add(overwrite=true,url='scimtasks.css')**

both errors point to line 1152 

    FetchClient.prototype.fetch = function (url, options) {
        return global.fetch(url, options);   <---1152
    };

Both are on-prem 2016.  Thanks in advance for your help.

**Comment by tavikukko** [comment]
Thanks for the details.
Only difference what i can see is the managed path /departments used in the failing site collection. The one what is working is using /sites. I will try to test this in my 2016 environment.

**Comment by tavikukko** [comment]
Hi,
I think the issue must be the filename  --> sc%2520suppliers%2520page.css
you have encoded spaces (%20) sc%20suppliers%20page.css in the filename, and then the filename gets re-encoded (% --> %25) to sc%2520suppliers%2520page.css and SharePoint does not find that .cs file anymore.

Remove the spaces from the filename and re-inject that css file to the site collection, i think that will fix your problem.

I recommend not to use spaces in filenames, you might encounter other issues as well in the future.

please let me know if that fixes your issues.

Thanks

**Comment by tavikukko** [comment]
Tested in SP2016 environment, added css file (my styles with spaces.css) to siteassets doclib under styles folder. Injected with and without encoding and Im able to save the file successfully.

http://intranet.sp.test/custompath/testsitecollection/_api/web/getFolderByServerRelativeUrl('%2Fcustompath%2Ftestsitecollection%2Fsiteassets%2Fstyles')/files('my%2520again%2520jee.css')

**Comment by tavikukko** [comment]
So what I need here is repro steps, because I cannot reproduce this in any of my environments.

Thanks

**Comment by jimbotronn** [comment]
Sorry I was off over the weekend. 
 I'm getting the same error. 
 https://[siteaddress]/departments/MaterielSystems/_api/web/getFolderByServerRelativeUrl('%2Fdepartments%2Fmaterielsystems%2Fstyle%2520library%2Fstyles')/files('schome.css')

I'm not sure how to get rid of %25 in the folder path.  I can't inject css using SP editor so i'm using script content web part to inject css for both sites.  I'm not sure why only one of sites is having issue when it used to work for it, too

**Comment by tavikukko** [comment]
can you share the snippet you add to script content, but please strip any content that you think is not secure to share. Then I might be able to repro this problem.
Thanks

**Comment by jimbotronn** [comment]
<link rel="stylesheet" type="text/css" href="/departments/MaterielSystems/Style Library/Styles/SCSuppliers.css"/>

**Comment by jimbotronn** [comment]
`<link rel="stylesheet" type="text/css" href="/departments/MaterielSystems/Style Library/Styles/SCSuppliers.css"/>
`

**Comment by tavikukko** [comment]
Thanks @jimbotronn for the snippet.
How do you add this snippet to the page, using script editor webpart?
You know, if you are using webpart to add this snippet, it will only work when you are actually in that page where the webpart is, not from any other page in the site collection... and that means that SP Editor will not be able to save this.

**Comment by jimbotronn** [comment]
I know. Our IT is terrible and haven't kept up with maintaining the
infrastructure. This is the only way I can work around their policies. The
script web part method works for the other site and it worked on the site
that I'm having issues with all through 2019. I honestly don't know why it
just now becoming an issue


Jimi Yu

**Comment by jimbotronn** [comment]
I've moved the files to a folder without space in its name and it worked. SP Editor is working again so I'm not sure why the folder name is just now becoming a problem but this workaround will do.

**Comment by jimbotronn** [comment]
Thanks for all your help

**Comment by tavikukko** [comment]
Thanks for the info.
I will be still trying to reproduce this couple of times. If there is anything you think could help me to repro this, just let me know.

Thanks
