### ISSUE TITLE
Cannot get PnP Js console to work

### ISSUE THREAD

**Issue by ytterstrom** [tavikukko/Chrome-SP-Editor#7]
I cannot get PnP JS console to work. Try to execute the default script, but the console shows "Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0". Am I missing something?

**Comment by tavikukko** [comment]
@ytterstrom are you logged in to SharePoint in you browser and viewing SharePoint page?

**Comment by ytterstrom** [comment]
Yes that is correct. SP2013.
![skarmklipp](https://cloud.githubusercontent.com/assets/18529706/23994259/67f9a3e6-0a44-11e7-891a-dbc0d10cadf9.PNG)

**Comment by tavikukko** [comment]
Ok, I will test in SP2013/SP2016 if i can reproduce.

**Comment by ytterstrom** [comment]
Tried on Office 365 site, and there it works as expected. Let me know if I can assist with something.

**Comment by tavikukko** [comment]
Just tested in SP2016 publishing site and it works ok. Is that page/site customised? custom masterpage? is that teams site? Can you provide more information. Could it be that running scripts are not allowed in that site?

**Comment by tavikukko** [comment]
Also works in SP2016 team site, just tested.

**Comment by ytterstrom** [comment]
It is a SP2013 teamsite. No custom masterpage. Scripts is allowed (have for example Jquery included as Custom action). I think I found a solution. If I add a script the following script it works: 
deferPnP(function () {
            $pnp.setup({
                headers: {
                    "Accept": "application/json; odata=verbose"
                }
            });

**Comment by tavikukko** [comment]
Ok. So you were trying to execute the default script provided by PnP JS Console and got the error? Then you changed the header to odata=verbose and it works?

**Comment by ytterstrom** [comment]
Yep, This is what I executed in order to get it to work:
import pnp from "pnp";
deferPnP(function () {
            pnp.setup({
                headers: {
                    "Accept": "application/json; odata=verbose"
                }
            });
  });
pnp.sp.web.lists.select("Title").get().then(result => {
	// gets all list titles from current web and writes them to console
	// hit 'ctrl + d' to test it :)
	console.log(result);
});

**Comment by ytterstrom** [comment]
By the way, can I see the javascript the Typescript in PnP JS Console is generating?

**Comment by tavikukko** [comment]
ok, thanks @ytterstrom! I think we are fine if i just add some guidance how to change the headers in case of error in on-premises. Thanks for working with issue! I will close the issue if you fine with the guidance?

Yes, you can see the javascript, you can click the link similar to this "VM693:25" in the chrome console output, on the right side.

**Comment by ytterstrom** [comment]
That sounds great! Thanks for a really nice extension that saves a ton of work
