### ISSUE TITLE
Can You please add link to sign out (useful for on-prems)

### ISSUE THREAD

**Issue by Gennady-G** [tavikukko/Chrome-SP-Editor#73]
Greetings @tavikukko !

By the way, if You have time - can You please add "Sign out" link to quick links?

![links-2020-04-22_155845](https://user-images.githubusercontent.com/5569346/79979207-31a28100-84b2-11ea-9779-63f479f4b2db.png)

Url is: 
`/_layouts/closeConnection.aspx?loginasanotheruser=true`

It is useful when need to change user working with on-prem sharepoint

Not an issue, but enhancement

Best regards, 
Gennady

**Comment by tavikukko** [comment]
Hi @Gennady-G !
Just tested this in online and it gives error:

Sorry, something went wrong
An unexpected error has occurred.

But it actually signs you out...

**Comment by Gennady-G** [comment]
Hmm...

Yes, it finally gives error in Online.. Also tried with` /_layouts/**15**/closeConnection.aspx?loginasanotheruser=true`

Just googled it. We can avoid error adding Source to url. Maybe something like this would be Ok?

`_layouts/closeConnection.aspx?loginasanotheruser=true&source=/_layouts/15/viewlsts.aspx`

Best regards, 
Gennady

**Comment by tavikukko** [comment]
Tried this and it logs you out and instantly start new sign-in process:

https://tenant.sharepoint.com/sites/sitecollection/_layouts/closeConnection.aspx?loginasanotheruser=true&source=https://tenant.sharepoint.com/sites/sitecollection

Can you verify in your online and on-prem envs and I will add it, if work in both?

Thanks

**Comment by Gennady-G** [comment]
Hi @tavikukko !

Yes, it works for me. But note that protocol could be **http**, and it fails if "https" is used шт second occurrence:

**http**://server/_layouts/closeConnection.aspx?loginasanotheruser=true&source=**http**://server

this is for my on-prem

Best regards, 
Gennady

**Comment by tavikukko** [comment]
nice!

yeah, all urls will be dynamic related to the current environment, not hardcoding anything.

So, I will have a look on this.

Thanks.

**Comment by Gennady-G** [comment]
Thank You much Tomi!)

**Comment by tavikukko** [comment]
Shipped in the latest version 5.5.7. Thanks @Gennady-G for the idea.
