### ISSUE TITLE
SP Editor is not available in the dev tools in New Edge Dev 

### ISSUE THREAD

**Issue by kblproactivedk** [tavikukko/Chrome-SP-Editor#74]
Version 84.0.488.1 (Official build) dev (64-bit)

Not sure that this will become an issue in the release version , but just in case

![image](https://user-images.githubusercontent.com/62996462/80361936-0a68fc80-8882-11ea-81ba-d0e7e6d37e0c.png)

**Comment by tavikukko** [comment]
Hi,
can you try to disable / enable it? Are you using beta build of Edge?

**Comment by kblproactivedk** [comment]
Hi, 
It used to work just fine using the version of SPEditor from the Google Web store. Yesterday it stopped working and I then removed the extention and installed the version from the Edge store.
Yes, I am on the beta/dev as stated above :-)

**Comment by tavikukko** [comment]
ok,
I had some similar issues when using dev/beta builds also. Then switched to official build and it started working. So it might be something in the dev builds.

**Comment by kblproactivedk** [comment]
Using SPEditor is way more important than testing the Dev builds, so I'll just change to the official build :-)  Thanks for a great tool

**Comment by tavikukko** [comment]
Can you confirm that moving to official build fixed your issue?

Thanks!

**Comment by kblproactivedk** [comment]
It seems to work fine once I switched to the official build :-)

**Comment by tavikukko** [comment]
Great,
Thanks @kblproactivedk for you help!
