### ISSUE TITLE
Can You please add "Login as another user" to on-prem context menu too?

### ISSUE THREAD

**Issue by Gennady-G** [tavikukko/Chrome-SP-Editor#75]
Hi Tomi!

As I understand these quick links are context sensitive..

They looks different in on-premise:

![on-prem-2020-05-06_123052](https://user-images.githubusercontent.com/5569346/81155774-5ad50e00-8f96-11ea-8e85-5854dcb87cc8.png)

and SharePoint Online:

![0365-2020-05-06_123123](https://user-images.githubusercontent.com/5569346/81155785-5dcffe80-8f96-11ea-86d8-a933eafafa7b.png)

Can You please make "Login as another user" available in on-premise environments too (now it is for O365 only)

Best regards, 
Gennady

**Comment by tavikukko** [comment]
Oops, sure will do, thanks!

**Comment by tavikukko** [comment]
this is now waiting for google's approval.

**Comment by Gennady-G** [comment]
Thank You much Tomi! Will be useful for me!

**Comment by tavikukko** [comment]
released in 5.5.8
