### ISSUE TITLE
More links

### ISSUE THREAD

**Issue by Rafaelki** [tavikukko/Chrome-SP-Editor#76]
Hi. I love this tool. May I suggest adding 2 more links:
1. In modern pages, to the maintenance mode > ?maintenancemode=true
2. To the new Term store admin > https://[tenant]-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/termStoreAdminCenter

**Comment by tavikukko** [comment]
Thanks @Rafaelki , I will have a look.

**Comment by Gennady-G** [comment]
Maybe also "Second-stage Recycle Bin" under "Recycle Bin"?..
/_layouts/15/AdminRecycleBin.aspx?View=2

Useful when You need to clean up recycle bins from old SPFx solutions..

![1-2020-06-05_171620](https://user-images.githubusercontent.com/5569346/83880505-4c724180-a750-11ea-9ba3-eb4c4b3a1d0e.png)

![2-2020-06-05_171629](https://user-images.githubusercontent.com/5569346/83880519-509e5f00-a750-11ea-8dd3-e72ed84c2597.png)

**Comment by tavikukko** [comment]
@Rafaelki, added these links to the latest version 5.5.9, thanks for the idea.
