### ISSUE TITLE
Sharepoint tab not shown in Dev tools

### ISSUE THREAD

**Issue by ReijerRaijmakers** [tavikukko/Chrome-SP-Editor#77]
I basicly used your extension to see if everything is installed in newly provisioned SharePoint Online sites. 
This has always worked, but since this week (from what i've noticed)  the tab is not shown in the Dev tools, which makes me unable to check the webhooks.

**Comment by ReijerRaijmakers** [comment]
Hi!

So whenever I am on a random site, google for example, I get to see this: 
![image](https://user-images.githubusercontent.com/24942034/84368561-0137b300-abd6-11ea-9c52-0772c015feda.png)

But whenever i get to a SharePoint site, that option disappears. 

This option has worked for atleast 6 months and somewhere between now and 2 weeks ago, it stopped working. My colleagues have the same problem. 

I tried reinstalling just now. did not fix it ;(

Thanks!

**Comment by tavikukko** [comment]
This is really interesting and strange, as I cannot repro this.
Does this happen with all devices and all SharePoint envs, online/onprem?
Could there be something in that environment, that is blocking SP Editor specifically ?

**Comment by ReijerRaijmakers** [comment]
Sorry for the late response.

It now works for a colleague of mine in chrome, still not for me. But it does work in edge for me so i can continue. 

Thanks for your advice!
