### ISSUE TITLE
Issue updating client_LocationBasedDefaults.html

### ISSUE THREAD

**Issue by joelfmrodrigues** [tavikukko/Chrome-SP-Editor#78]
Hi Tomi,

I tried to edit the file where default field values configuration for a library (Forms>client_LocationBasedDefaults.html) are stored using the extension but was not able to save my changes. Tried multiple times and always had the same result: stuck with saving animation.

I then went on SharePoint Designer and noticed that the file was checked-out, likely by the extension.
Any idea if this could be a bug or just user error?

Thanks!

**Comment by Gennady-G** [comment]
Greetings!

`was not able to save my changes.`
`noticed that the file was checked-out`

I'm not an author, but sometimes there is an error when there are too much versions (about 100, not sure, depending of library settings).
You can try to remove all file versions, and then check-in file again

Best regards, Gennady

**Comment by tavikukko** [comment]
Hi @joelfmrodrigues and thanks for the issue.
I tested and I also get the error. The error comes when it is doing check-in for the file, but I think in this case its not necessary as we saving system file in reality. **The file gets updated thou**, so I think we need to check some conditions before actually doing the check-in if its needed. Thanks @Gennady-G  also for you help here!

**Comment by tavikukko** [comment]
@joelfmrodrigues, I updated SP Editor, made small fix for this, I hope it was enough. Let me know if it did not work, thanks!
