### ISSUE TITLE
Updating site script not working for some scripts

### ISSUE THREAD

**Issue by Kizlyk** [tavikukko/Chrome-SP-Editor#79]
Hi, 

Steps to reproduce 
F12 -> Sharepoint -> Site Scripts -> Select existing script -> Make Changes -> Press Save
As a result spinner keeps spinning indefinitely, save is not happening.

Works fine for some other scripts I have. If there is an error there it would be nice to see it

**Comment by tavikukko** [comment]
Hi @Kizlyk ,
Could you check the **network tab** when you get the error, there might be failing request and from there we could see the error from the response.

**Comment by Kizlyk** [comment]
Hi @tavikukko,

I checked, unfortunately there are no failed request there. I see the successful call to _api/Microsoft.Sharepoint.Utilities.WebTemplateExtensions.SiteScriptUtility.GetSiteScripts and then to _api/contextinfo. What else can you suggest I could do to debug this?

Thanks

**Comment by tavikukko** [comment]
Thanks @Kizlyk 
What we can try next, is that when you have the SP Editor open in the devtools, right click the tool somewhere and select inspect. That will open the devtools of the SP Editor and from there in console tab, you might see the underlying error.
![image](https://user-images.githubusercontent.com/2223355/88667225-c0462000-d0e9-11ea-9b84-12142ddc8365.png)

**Comment by Kizlyk** [comment]
Thanks @tavikukko . I Tried that, unfortunately no errors there either:
![Image 1](https://user-images.githubusercontent.com/37625742/88670298-9131ad80-d0ed-11ea-9a5a-598f080507c6.png)

I will have to update the script some other way, but if you want me to try something else to debug it, please let me know

**Comment by tavikukko** [comment]
ok, could i have a look at the site script?

**Comment by Kizlyk** [comment]
I would prefer not to post it here. I could email it to you I suppose

**Comment by tavikukko** [comment]
Ok, first dot last at gmail dot com 

And please xyz all sensitive info, thanks.

**Comment by tavikukko** [comment]
@Kizlyk, I'm closing this, please open it again if you can provide repro steps, thanks!
