### ISSUE TITLE
Error loading all Properties (Search)

### ISSUE THREAD

**Issue by kasperbolarsen** [tavikukko/Chrome-SP-Editor#81]
Latest version, just added from the Chrome store
Doing a Seach using a Search Result Source guid ( * in Query) the rest is default

The results shows up just fine, but the "Show all properties" shows an error ( looks like it is expecting a refiner)
![image](https://user-images.githubusercontent.com/20593570/100234961-16a65c80-2f2c-11eb-9b5f-983ae4b7cf54.png)

**Comment by tavikukko** [comment]
Thanks @kasperbolarsen , I will have a look!

**Comment by kasperbolarsen** [comment]
Hi Tomi, FYI it seems only to be an issue when using people search :-) Great work, I have SP Editor on each profile, both in Edge and Chrome

**Comment by tavikukko** [comment]
fixed, waiting for approval in Google webstore.

**Comment by tavikukko** [comment]
Fixed in the latest release of [SP Editor v5.6.3](https://chrome.google.com/webstore/detail/sp-editor/ecblfcmjnbbgaojblcpmjoamegpbodhd)
