### ISSUE TITLE
Error: Field or property "storageentitiesindex" does not exist.

### ISSUE THREAD

**Issue by araver** [tavikukko/Chrome-SP-Editor#85]
I'm getting this error on "Modern Properties" tab in SharePoint online.  The property does exist on the webs property bag. See images.

![image](https://user-images.githubusercontent.com/31546277/103812984-912ec580-501c-11eb-9eb0-3847d42c461d.png)
![image](https://user-images.githubusercontent.com/31546277/103812994-955ae300-501c-11eb-8ab6-723f9156441f.png)

**Comment by tavikukko** [comment]
Hi @araver 
To use Modern Properties, you need to be in the admin site, eg. yourternant-admin.sharepoint.com

**Comment by tavikukko** [comment]
closing, as no further question.
