### ISSUE TITLE
SP2019 on-prem, classic, $pnp.SPNS.Web is not a constructor

### ISSUE THREAD

**Issue by Gennady-G** [tavikukko/Chrome-SP-Editor#87]
Hi @tavikukko !

Looks like it basically works, but don't see green confirmation popup that file is saved/approved, 

![0-2021-02-03_175553](https://user-images.githubusercontent.com/5569346/106757251-8ed68000-6649-11eb-810b-0c5dcf9a46b1.png)

and also sometimes get this error:

`VM10995:73 Uncaught (in promise) TypeError: $pnp.SPNS.Web is not a constructor`
![1-git-2021-02-03_175340](https://user-images.githubusercontent.com/5569346/106757265-93029d80-6649-11eb-955e-3b5470724927.png)

SP 2019, Classic page, Chrome Version 88.0.4324.146 (Official Build) (64-bit), Win Server 2019

upd.: no, it works only until f12 console is active. It does not save, as I understand..

**Comment by tavikukko** [comment]
Could you test if this happens also in online, thanks. And thank you for reporting the issue👌

**Comment by Gennady-G** [comment]
Hi!

Checked. Yes, same in Online.

![not-a-constructor-2021-02-03_202340](https://user-images.githubusercontent.com/5569346/106776861-e4b52300-665d-11eb-9249-164b1d3e6f62.png)

Site template is STS#0, classic

Best regards, Gennady

**Comment by tavikukko** [comment]
Fixed, release waiting for Googles approval.

**Comment by tavikukko** [comment]
Fix released in version 5.6.8. Thanks again @Gennady-G for ypur help 👍

**Comment by Gennady-G** [comment]
Thank You too for great tool! :)

**Comment by Gennady-G** [comment]
Now works, thank You much!)

Best regards, Gennady
