### ISSUE TITLE
How did you get to the MGT-React play ground

### ISSUE THREAD

**Issue by Ofer-Gal** [tavikukko/Chrome-SP-Editor#88]
I saw your great demo on PnP today.
you showed how to interact with MGT-react and your samples.
I have latest version but I don't see how to get there.

Thanks in advance.

Found it on the Edge extension.
Great tool thank you much

**Comment by Ofer-Gal** [comment]
Now I have a real Issue :-)
When I change the clientId in the Msal Provider, it tells me I can only use Multi tenant. So I change my registered App to be Multi tenant.
Then next login it shows error:AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application:{my application ID}
 I added the root of my SPO https://mycompny.sharepoint.com/ as Redirect URI (there is no reply URL) but it is still erroring.
Any idea?

Thanks again

**Comment by Gennady-G** [comment]
> I saw your great demo on PnP today.
> you showed how to interact with MGT-react and your samples.

@Ofer-Gal can You please provide direct link or title of the video?

**Comment by Ofer-Gal** [comment]
I really can't remember the exact demo but it is one of the PnP  https://www.youtube.com/playlist?list=PLR9nK3mnD-OWSbg0o9a7mx_E7s2u7h_o2

**Comment by Gennady-G** [comment]
Ah, Ok! Thank You @Ofer-Gal, looks like I've  found it:
https://www.youtube.com/watch?v=2NuhuYyWNB0&list=PLR9nK3mnD-OWSbg0o9a7mx_E7s2u7h_o2&index=23

Best regards!
