### ISSUE TITLE
Page layout switcher doesn't initialize on some pages

### ISSUE THREAD

**Issue by AgileSpiff** [tavikukko/Chrome-SP-Editor#89]
Follow up to a post I left on the Chrome Web Store (as Neil). To reiterate, I posted that the page layout switcher had stopped working for me. In a later post I mentioned that it worked when I tried it in a different SharePoint Online tenant, and I speculated that the first tenant's IT may have done something to break it.

Now I find that it works in the first tenant, too, just not on the page I need to switch from Article Page to Home Page layout. It seems there is something about this page that is breaking it. The page is quite simple, composed only of out-of-box web parts, so I am stumped as to what the problem is.

Happy to provide further details - just let me know what information is needed!

**Comment by tavikukko** [comment]
Hi and thank you for creating issue!
Is it so, that you do not even see that dropdown layout selector in the menu? Or when selecting the layout and saving does not have effect?

**Comment by AgileSpiff** [comment]
Hello,

It's the first situation - the layout selector dropdown does not appear on the affected page:

![image](https://user-images.githubusercontent.com/35044051/110705477-4e6ba400-81ab-11eb-899e-620feca19568.png)

**Comment by rockanand** [comment]
Hello,

I have created templates based out of Home page layout. ("Set-PnpListItem -Identity "Id" - Values @{"PageLayoutType"="Home"}.

User trying to create new modern page based out of this Home page template will have provision to key in PageName in the banner section for the very first time (which is expected). Once after page has been saved as draft/submit your banner section disappears (expected)..

However from march 21 this behavior doesn't seems to work.

There is no banner section while creating new page, making them not to key in page name. As a result user couldn't create new page in Prod site.

Have contacted Microsoft but they couldn't support much on this ticket.

Your assistance herein would be greatly appreciated.

Regards

**Comment by tavikukko** [comment]
Can't repro this, can I get repro instructions, thanks! @AgileSpiff @rockanand

**Comment by tavikukko** [comment]
This is now fixed, will be part of version 5.6.13
