### ISSUE TITLE
'Classic Admin Center' url update

### ISSUE THREAD

**Issue by Gennady-G** [tavikukko/Chrome-SP-Editor#92]
Hi @tavikukko !

This is not a bug a small change..

Classic Site collections page is now deprecated:

`https://server-admin.sharepoint.com/_layouts/15/online/SiteCollections.aspx`

now is:
`https://server-admin.sharepoint.com/_layouts/15/online/AdminHome.aspx#/siteManagement/view/CLASSIC%20SITES`

![1-2021-06-15_170215](https://user-images.githubusercontent.com/5569346/122057184-67fc3780-cdfb-11eb-94b3-12785c128a2e.jpg)
![2-2021-06-15_170234](https://user-images.githubusercontent.com/5569346/122057189-69c5fb00-cdfb-11eb-9da5-896dc4ebd562.jpg)

**Comment by tavikukko** [comment]
Thanks @Gennady-G , will fix that!

**Comment by tavikukko** [comment]
This will be out when Google approves the latest version 5.6.10 , thanks for reporting!

**Comment by Gennady-G** [comment]
Thank You @tavikukko! :)
