### ISSUE TITLE
Search not showing result

### ISSUE THREAD

**Issue by alooft** [tavikukko/Chrome-SP-Editor#93]
When performing a search using the SP Editor search tab, the search is executed correctly as seen from the Network log, but nothing is shown in the result page (not even an empty table).

This happens across multiple Chrome profiles, PCs and SharePoint tenants.

I can not see any info in the console.

**Comment by tavikukko** [comment]
Thanks @alooft , I will have a look.

**Comment by MarkusLanger** [comment]
The same behaviour in my case.

**Comment by tavikukko** [comment]
Cannot repro this, can you please provide more information @alooft @MarkusLanger ?

**Comment by MarkusLanger** [comment]
The problem does not exist in all tenants. I attached a video and the response of the the search request. I hope it helps.


https://user-images.githubusercontent.com/12131918/123594814-73366680-d7f0-11eb-935b-47a79f878d9e.mp4

[Response.txt](https://github.com/tavikukko/Chrome-SP-Editor/files/6724132/Response.txt)

**Comment by tavikukko** [comment]
Thanks @MarkusLanger 
Can you try the following: when SP Editor is open, right click it and Inspect. This will open the devtools of the editor. Now run the search again, you should see the error message in the devtoold of SP Editor. I would be interested to see the error message.

**Comment by tavikukko** [comment]
Also interested the difference between tenants and the sitetype of the current page you have open when running the search and other tenant/site work and other not, thanks.

**Comment by tavikukko** [comment]
ok, I found a tenant where I can repro this. Lets see whats the problem.

**Comment by MarkusLanger** [comment]
I don't get an error in the console of the SP Editor devtools.

**Comment by tavikukko** [comment]
I found the issue. Some tenant do not set **elapsedTime** property, always returns 0. For some reason I have used that property to check that the search was successful. Will fix this asap. Thanks @MarkusLanger for you help!

**Comment by tavikukko** [comment]
Fix will be out when Google approves the latest version 5.6.10 , thanks for your cooperation!

**Comment by MarkusLanger** [comment]
Works fine. Thanks for the quick solution.
![image](https://user-images.githubusercontent.com/12131918/123756976-c6c2b600-d8bd-11eb-9a0e-9ab7b1f857b4.png)
