### ISSUE TITLE
Missing from chrome webstore

### ISSUE THREAD

**Issue by Tanddant** [tavikukko/Chrome-SP-Editor#97]
The extension seems to have been pulled from the chrome webstore, is this a known issue?

**Comment by tavikukko** [comment]
Hi,
yes, I got email from the store, that in the description of the extension there is word "Updated" repeated too many times... so they removed it, amazing. I have removed the "illegal" words from the description and pushed it back, but need to wait Chrome Store to review it first.

**Comment by tavikukko** [comment]
SP Editor approved and back in the store.
