### ISSUE TITLE
How can we use Modern Scriptlinks (not an issue but question)?

### ISSUE THREAD

**Issue by Gennady-G** [tavikukko/Chrome-SP-Editor#98]
Hi @tavikukko !

Occasionally noticed that Edge version has "Modern Scriptlink App", that installs *.sppkg in App Catalog.

How can I use it? What code should be in js file?

For example earlier CSR was registered like this (this is example of code generated by Cisar, https://github.com/andrei-markeev/cisar):

```
SP.SOD.executeFunc("clienttemplates.js", "SPClientTemplates", function () {
    function getBaseHtml(ctx) {
        return SPClientTemplates["_defaultTemplates"].Fields.default.all.all[ctx.CurrentFieldSchema.FieldType][ctx.BaseViewID](ctx);
    }
    function init() {
        SPClientTemplates.TemplateManager.RegisterTemplateOverrides({
            // OnPreRender: function(ctx) { },
            Templates: {
                //     View: function(ctx) { return ""; },
                //     Header: function(ctx) { return ""; },
                //     Body: function(ctx) { return ""; },
                //     Group: function(ctx) { return ""; },
                //     Item: function(ctx) { return ""; },
                //     Fields: {
                //         "<field internal name>": {
                //             View: function(ctx) { return ""; },
                //             EditForm: function(ctx) { return ""; },
                //             DisplayForm: function(ctx) { return ""; },
                //             NewForm: function(ctx) { return ""; }
                //         }
                //     },
                //     Footer: function(ctx) { return ""; }
            },

            // OnPostRender: function(ctx) { },
            ListTemplateType: 171
        });
    }
    RegisterModuleInit(SPClientTemplates.Utility.ReplaceUrlTokens("~siteCollection/Style Library/delme.js"), init);
    init();
});
```
What type of js can we use in Modern Scriptlink? Maybe You have some example?

Best regards, Gennady

**Comment by tavikukko** [comment]
Hi @Gennady-G !

Just create javascript file and drop it to a folder in SP. Then inject that file using SP Editor's ScriptLinks functionality. Now, if you have installed the Modern ScriptLink App, the file you injected will be loaded when opening page in the injected files scope.

The source code of Modern ScriptLinks App can be found here [https://github.com/tavikukko/sp-scriptlinks](https://github.com/tavikukko/sp-scriptlinks)

I hope this helps,
Tomi

**Comment by Gennady-G** [comment]
> The source code of Modern ScriptLinks App can be found here https://github.com/tavikukko/sp-scriptlinks

So as I've understand - it is something like 'Dynamic Application Customizer', that can append different js files to page header

But what should be inside js file?

I tried to add App to site-collection, uploaded file with "console.log('Hi!')" but don't see if it is loaded..
Or I do something wrong..
My url is: `https://server.sharepoint.com/sites/dev/SiteAssets/scriptlink.js`

![11-2022-01-13_164733](https://user-images.githubusercontent.com/5569346/149332769-b3e5f1db-5703-480e-a818-77ef0de334fe.jpg)

![s2-2022-01-13_163900](https://user-images.githubusercontent.com/5569346/149331975-a635c65a-27e2-4477-957a-b3f28f6f9533.jpg)

![s3-2022-01-13_163916](https://user-images.githubusercontent.com/5569346/149331984-078b539a-01cf-45d9-8c45-0f53291fe715.jpg)

![s4-2022-01-13_163928](https://user-images.githubusercontent.com/5569346/149331990-f56c7316-ef7c-47ee-87f2-72f64af5b086.jpg)

**Comment by Gennady-G** [comment]
App is deployed successfully:

![app-2022-01-13_165237](https://user-images.githubusercontent.com/5569346/149333535-1a6de30d-3159-4266-a319-32875f41d3dc.jpg)

**Comment by visma-tomi-tavela** [comment]
Ok, I need to check if that App still works as it should. But it just loads that file what you have injected and execute it, that's all. So the console.log just print something.

**Comment by tavikukko** [comment]
Ok, I need to check if that App still works as it should. But it just loads that file what you have injected and execute it, that's all. So the console.log just print something.

**Comment by Gennady-G** [comment]
Ah, ok! so I don't see it in Network tab.. But it prints nothing in console, too..

**Comment by tavikukko** [comment]
Change the scope to sitecollection in the ScriptLink.

**Comment by tavikukko** [comment]
Seems like the App only reads sitecollection links. But anyways, I don't think people should use sub webs with Modern SharePoint.

**Comment by Gennady-G** [comment]
Wow!
Thank You much @tavikukko , as usual! :)
Now it works perfect!)

![hi-2022-01-13_174128](https://user-images.githubusercontent.com/5569346/149340680-fa8548d3-3ceb-46e1-969a-3465c523074d.jpg)
